### ISSUE TITLE
Max zoom level is 21

### ISSUE THREAD

**Issue by frozenpandaman** [doersino/gomati#1]
Works perfectly, thank you so much for this simple script!

Just a note that zoom levels can actually go up to 21, vs. 20 which the [comment](https://github.com/doersino/gomati/blob/c553bdccb59b1472ef8975e37fcedea691527495/gomati.sh#L95) says (and if you specify anything higher than that, the script still allows you to proceed – albeit the progress bar is red – but then throws an error at the very end during the stitching step).

**Comment by doersino** [comment]
Thanks for the heads up. The maximum available zoom level is actually 23, but tile availability at this level is [very rare](https://stackoverflow.com/a/32407072). I'm about to commit a change explaining all that – thanks again!

**Comment by frozenpandaman** [comment]
Ah, cool – and huh, interesting! Sounds good. Thank you as well!
